### ISSUE TITLE
HTTP error (400): <html><head><title>Error</title></head><body>The I/O operation has been aborted because of either a thread exit or an application request.

### ISSUE THREAD

**Issue by ylluminate** [mabarroso/ocr#1]
Hi, we're using an unlimited account version of free_ocr and have seen an error where it returns the following once in a while:

```
19:52:57 web.1     | E, [2012-03-26T19:52:57.277574 #94789] ERROR -- : undefined method `[]' for false:FalseClass (NoMethodError)
19:52:57 web.1     | /Volumes/Users/username/ruby/rails/project/config/initializers/server_ip.rb:13:in `<top (required)>'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:234:in `load'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:234:in `block in load'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `block in load_dependency'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640:in `new_constants_in'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `load_dependency'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:234:in `load'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/engine.rb:556:in `block (2 levels) in <class:Engine>'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/engine.rb:555:in `each'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/engine.rb:555:in `block in <class:Engine>'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/initializable.rb:30:in `instance_exec'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/initializable.rb:30:in `run'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/initializable.rb:54:in `each'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/initializable.rb:54:in `run_initializers'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/application.rb:96:in `initialize!'
19:52:57 web.1     | /Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/railties-3.1.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
19:52:57 web.1     | /Volumes/Users/username/ruby/rails/project/config/environment.rb:5:in `<top (required)>'
```

How do I handle an error like this?  It seems it's within your methods or calls.  I'm simply calling it with your example:  `ocr.recognize`

**Comment by mabarroso** [comment]
Sorry, but I didn't found ocr references in log lines. I tested the gem whith a simple ruby script and a rails app (Rails 3.1.3) and work fine.

My apologize, but I only can test for 100x100 images.

Please, could you try run this script to complete the test? Make a simple script or copy/paste in irb. You must provide a 100x100 image for test.

``` ruby
require 'ocr'
ocr = OCR.use :free_ocr
ocr.file= 'test_100x100.png'
ocr.recognize
puts "ERROR: #{ocr.error}" if ocr.error?
puts "RESULT: #{ocr.text}" unless ocr.error?
```

**Comment by ylluminate** [comment]
Yes, I'm using smaller than 100x100 images, that's not a problem.  The real problem I have is that when `ocr.recognize` runs, it sometimes fails for various reasons.  For example, a moment ago it simply had a network connection reset: 

```
Connection reset by peer
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/protocol.rb:141:in `read_nonblock'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/protocol.rb:92:in `read'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:2755:in `read_body_0'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:2710:in `read_body'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:2735:in `body'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:2672:in `reading_body'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:1321:in `block in transport_request'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:1293:in `request'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/httpi-0.9.6/lib/httpi/adapter/net_http.rb:23:in `block in get'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/httpi-0.9.6/lib/httpi/adapter/net_http.rb:76:in `block in do_request'
/Users/username/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:745:in `start'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/httpi-0.9.6/lib/httpi/adapter/net_http.rb:75:in `do_request'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/httpi-0.9.6/lib/httpi/adapter/net_http.rb:22:in `get'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/httpi-0.9.6/lib/httpi.rb:86:in `block in get'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/httpi-0.9.6/lib/httpi.rb:194:in `with_adapter'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/httpi-0.9.6/lib/httpi.rb:84:in `get'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/savon-0.9.9/lib/savon/wasabi/document.rb:34:in `resolve_document'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/savon-0.9.9/lib/savon/wasabi/document.rb:15:in `xml'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/wasabi-2.1.0/lib/wasabi/document.rb:120:in `xml?'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/wasabi-2.1.0/lib/wasabi/document.rb:132:in `guard_parse'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/wasabi-2.1.0/lib/wasabi/document.rb:125:in `parser'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/wasabi-2.1.0/lib/wasabi/document.rb:36:in `endpoint'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/savon-0.9.9/lib/savon/client.rb:109:in `preconfigure'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/savon-0.9.9/lib/savon/client.rb:75:in `request'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/ocr-0.3.0/lib/ocrs/free_ocr.rb:22:in `ocr_recognize'
/Users/username/.rvm/gems/ruby-1.9.3-p125@all/gems/ocr-0.3.0/lib/ocr/ocr.rb:55:in `recognize'
```

My question is not about this working properly, but simply that errors need to be handled better when the server on the other side receiving the submission from the gem fails.  It needs to simply handle the problem more gracefully and allow an error to be returned...  from the example you give I don't see a solution since `ocr.recognize` fails internally and does not give me a chance to catch and handle the exception.  Or am I wrong and missing how to use your gem?

**Comment by mabarroso** [comment]
oh, I see. It is a big mistake. I will try to throw an exception and set the error? method. Also, I will create a new method to enable/disable exceptions.

**Comment by ylluminate** [comment]
Thanks, that is wonderful!  It will help a lot as it really get's ugly when tracking logs.  I'd like to handle these better and then be able to rerun the recognize command a few times on failure vs just failing altogether.  THANK YOU!!!

**Comment by ylluminate** [comment]
Any updates on this @mabarroso?  We'd hoped to see your additions to this great gem with regards to exception handling.  Or is there a way we could perhaps help?  We've just not dug into what you're doing and not familiar with your efforts so far, but if you think it's going to take a while to get it up, please do let me know.  Thanks again!

**Comment by mabarroso** [comment]
I pushed all changes and release 

Now, any exception are catched and set ocr.error? method

The auto rescue exceptions could be disabled setting ocr.rescue_exceptions= false

Please, tell me about to reopen issue if necessary.

Thank you. Any suggestions are welcome
